jupyterhub:
  prePuller:
    continuous:
      enabled: false
  singleuser:
    lifecycleHooks:
      postStart:
        exec:
          command: ["rsync", "/etc/default-home-contents/", "/home/jovyan"]
          #command: ["gitpuller", "https://github.com/spacetelescope/jupyterhub-user-content", "roman-sit", "."]
    extraEnv:
      # CRDS Environment variables
      CRDS_PATH: /home/jovyan/crds_cache
      CRDS_SERVER_URL: https://jwst-serverless.stsci.edu
      CRDS_S3_ENABLED: "1"
      CRDS_S3_RETURN_URI: "0"
      CRDS_MAPPING_URI: "s3://dmd-test-crds/mappings/jwst"
      CRDS_REFERENCE_URI: "s3://dmd-test-crds/references/jwst"
      CRDS_CONFIG_URI: "s3://dmd-test-crds/config/jwst"
      CRDS_USE_PICKLES: "0"
      CRDS_DOWNLOAD_MODE: plugin
      CRDS_DOWNLOAD_PLUGIN: 'crds_s3_get ${SOURCE_URL} ${OUTPUT_PATH} ${FILE_SIZE} ${FILE_SHA1SUM}'
    defaultUrl: "/lab"
    memory:
      guarantee: 512M
      limit: 1G
  hub:
    extraConfig:
      jupyterlab: |
        c.Spawner.cmd = ['jupyter-labhub']
  proxy:
    https:
      enabled: false
      hosts:
        - roman-sit.science.stsci.edu
  auth:
    # change this when we setup oauth
    #    type: dummy
    #dummy:
    #  password: password

    type: custom
    custom:
      className: oauthenticator.generic.GenericOAuthenticator
      config:
        login_service: "auth0"
        token_url: "https://auth.mast.stsci.edu/oauth/access_token"
        userdata_method: GET
    users:
      - cslocum
      - yuvi
      - gough
    admin:
      users:
        - cslocum
